name: Build APK with Audio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Устанавливаем зависимости для TTS
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gTTS

      # 4️⃣ Генерация аудио файлов
      - name: Generate audio
        run: |
          mkdir -p app/src/main/res/raw
          python generate_audio.py

      # 5️⃣ Устанавливаем Java (для Gradle)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 6️⃣ Устанавливаем Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.1

      # 7️⃣ Сборка APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 8️⃣ Сохраняем APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: FastEnglish-debug
          path: app/build/outputs/apk/debug/app-debug.apk
